name: pr-check
on:
  pull_request:
    branches:
      - "main"
jobs:
  format-check:
    name: code check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: black
        uses: rickstaa/action-black@v1
        with:
          black_args: ". --check"
      - name: mypy
        uses: jpetrucciani/mypy-check@master
        with:
          mypy_flags: "--ignore-missing-imports"
