name: pr-check
on:
  pull_request:
    branches:
      - "main"
jobs:
  format-check:
    name: black formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rickstaa/action-black@v1
        with:
          black_args: ". --check"
